In [2]:
import numpy as np

In [3]:
a=np.array([3,6,9])
a[2]

np.int64(9)

In [4]:
a=np.array([3,6,9]) #dimention of array
a.ndim


1

In [11]:
a=np.array([[2,5],[4,7],[9,3]]) #size for each element
a.itemsize

8

In [12]:
a.dtype #data type


dtype('int64')

In [14]:
a=np.array([[4,6],  #array shape
       [7,8],
       [9,3]])
a.shape

(3, 2)

In [15]:
a.reshape(2,3)

array([[4, 6, 7],
       [8, 9, 3]])

In [16]:
a.ravel()

array([4, 6, 7, 8, 9, 3])

In [17]:
a.min()

np.int64(3)

In [18]:
a.max()

np.int64(9)

In [19]:
a.sum()

np.int64(37)

In [20]:
a.sum(axis=1)

array([10, 15, 12])

In [21]:
a=np.array([[2,5],[7,9]])
b=np.array([[2,4],[6,8]])
a+b

array([[ 4,  9],
       [13, 17]])

In [22]:
a*b

array([[ 4, 20],
       [42, 72]])

In [23]:
a/b

array([[1.        , 1.25      ],
       [1.16666667, 1.125     ]])

In [1]:
import numpy as np
n=[3,5,6]
n[0:2]

[3, 5]

In [2]:
n[-1]

6

In [3]:
a=np.array([[6,8,3],
           [2,9,5],
           [5,7,1]])
a[1,2]

np.int64(5)

In [4]:
a[-1]

array([5, 7, 1])

In [5]:
for row in a:
    print(row)

[6 8 3]
[2 9 5]
[5 7 1]


In [6]:
a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [7]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [9]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [11]:
a[b]=-1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [13]:
a=np.arange(12).reshape(3,4)
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [14]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
 for x in np.nditer(a,order='F'):
     print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [25]:
 for x in np.nditer(a,order='C'):
     print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [28]:
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=x*x

In [29]:
a

array([[    0,     1,    16,    81],
       [  256,   625,  1296,  2401],
       [ 4096,  6561, 10000, 14641]])

In [2]:
a=np.array([20,40,7,9])
print(np.append(a,50))

[20 40  7  9 50]


In [3]:
print(np.insert(a,1,70)) #array,index,value

[20 70 40  7  9]


In [5]:
print(np.delete(a,1))

[20  7  9]


In [6]:
print(np.sort(a))

[ 7  9 20 40]


In [8]:
s=np.where(a==40)
print(s)

(array([1]),)
